import { NextRequest } from "next/server";
import { getEvent } from "@/lib/events";
import { buildContextWindow, SYSTEM_LIVE } from "@/lib/prompts";
import { mimoText, isMimoFallback } from "@/lib/mimo";
import { mockCommentarySSE } from "@/lib/mock";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * GET /api/commentary?eventId=ftx-collapse&cursor=1668006180000
 *
 * Streams Server-Sent Events. With MIMO_API_KEY + credits, narration is
 * generated by xiaomi/mimo-v2.5-pro. Without credits or on upstream failure,
 * falls back to a deterministic corpus-based summary tagged "(corpus mode)".
 */
export async function GET(req: NextRequest) {
  const url = new URL(req.url);
  const eventId = url.searchParams.get("eventId") ?? "";
  const cursor = Number(url.searchParams.get("cursor") ?? "0");
  const event = getEvent(eventId);

  if (!event || !cursor) {
    return new Response(
      JSON.stringify({ error: "missing eventId or cursor" }),
      { status: 400, headers: { "Content-Type": "application/json" } },
    );
  }

  const context = buildContextWindow(event, cursor);
  const userMsg = `Narrate what is happening at the cursor right now. Use the corpus below.\n\n${context}`;

  try {
    const upstream = await mimoText({
      stream: true,
      temperature: 0.35,
      maxTokens: 600,
      messages: [
        { role: "system", content: SYSTEM_LIVE },
        { role: "user", content: userMsg },
      ],
    });
    return new Response(upstream.body, {
      headers: {
        "Content-Type": "text/event-stream; charset=utf-8",
        "Cache-Control": "no-cache, no-transform",
        Connection: "keep-alive",
        "x-chronos-source": "mimo",
      },
    });
  } catch (e) {
    if (isMimoFallback(e)) {
      return new Response(mockCommentarySSE(event, cursor), {
        headers: {
          "Content-Type": "text/event-stream; charset=utf-8",
          "Cache-Control": "no-cache",
          "x-chronos-source": "corpus",
        },
      });
    }
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "upstream" }),
      { status: 502, headers: { "Content-Type": "application/json" } },
    );
  }
}
